# Generated by Django 3.2.5 on 2021-07-29 14:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ipam", "0048_prefix_populate_depth_children"),
        ("dcim", "0131_consoleport_speed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ASN",
            fields=[
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("organization_name", models.CharField(max_length=100, unique=True)),
                (
                    "number",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4294967294),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AS Numbers",
            },
        ),
        migrations.CreateModel(
            name="BGPPeerGroup",
            fields=[
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("maximum_prefixes", models.PositiveIntegerField()),
                (
                    "asn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="netbox_cmdb.asn",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "BGP Peer Groups",
            },
        ),
        migrations.CreateModel(
            name="RoutePolicy",
            fields=[
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Routing Policies",
            },
        ),
        migrations.CreateModel(
            name="DeviceBGPSession",
            fields=[
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("maximum_prefixes", models.PositiveIntegerField()),
                (
                    "asn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="netbox_cmdb.asn",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devicebgpsessiondevice",
                        to="dcim.device",
                    ),
                ),
                (
                    "local_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_address",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "peer_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="netbox_cmdb.bgppeergroup",
                    ),
                ),
                (
                    "route_policy_in",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devicebgpsessionroute_policy_in",
                        to="netbox_cmdb.routepolicy",
                    ),
                ),
                (
                    "route_policy_out",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devicebgpsessionroute_policy_out",
                        to="netbox_cmdb.routepolicy",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Device BGP Sessions",
            },
        ),
        migrations.AddField(
            model_name="bgppeergroup",
            name="route_policy_in",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bgppeergrouproute_policy_in",
                to="netbox_cmdb.routepolicy",
            ),
        ),
        migrations.AddField(
            model_name="bgppeergroup",
            name="route_policy_out",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bgppeergrouproute_policy_out",
                to="netbox_cmdb.routepolicy",
            ),
        ),
    ]
