# Generated by Django 3.2.5 on 2021-08-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_cmdb", "0002_circuit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicebgpsession",
            name="maximum_prefixes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="devicebgpsession",
            name="peer_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="netbox_cmdb.bgppeergroup",
            ),
        ),
        migrations.CreateModel(
            name="BgpSession",
            fields=[
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(default="active", max_length=50)),
                ("password", models.CharField(blank=True, max_length=100)),
                (
                    "circuit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="netbox_cmdb.circuit",
                    ),
                ),
                (
                    "peer_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_a",
                        to="netbox_cmdb.devicebgpsession",
                    ),
                ),
                (
                    "peer_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_b",
                        to="netbox_cmdb.devicebgpsession",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "BGP Sessions",
            },
        ),
    ]
