# Generated by Django 3.2.8 on 2021-11-17 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0004_rework_bgp_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgpcommunitylistterm',
            options={'ordering': ['sequence'], 'verbose_name_plural': 'BGP community list terms'},
        ),
        migrations.AlterModelOptions(
            name='prefixlistterm',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterModelOptions(
            name='routepolicyterm',
            options={'ordering': ['sequence'], 'verbose_name_plural': 'Route Policy terms'},
        ),
        migrations.AlterField(
            model_name='bgpcommunitylistterm',
            name='bgp_community_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgp_community_list_term', to='netbox_cmdb.bgpcommunitylist'),
        ),
        migrations.AlterField(
            model_name='prefixlistterm',
            name='prefix_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefix_list_term', to='netbox_cmdb.prefixlist'),
        ),
        migrations.AlterField(
            model_name='routepolicyterm',
            name='route_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_policy_term', to='netbox_cmdb.routepolicy'),
        ),
    ]
