# Generated by Django 3.2.8 on 2021-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0005_alter_ordering_and_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgppeergroup',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicebgpsession',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
