# Generated by Django 3.2.8 on 2021-11-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0006_remove_nullable_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepolicyterm',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
