# Generated by Django 3.2.11 on 2022-01-19 09:23

from django.db import migrations


def save_route_pol_fk(apps, schema):
    BGPPeerGroup = apps.get_model("netbox_cmdb", "BGPPeerGroup")
    DeviceBGPSession = apps.get_model("netbox_cmdb", "DeviceBGPSession")
    AfiSafi = apps.get_model("netbox_cmdb", "AfiSafi")

    for peer_group in BGPPeerGroup.objects.all():
        if peer_group.route_policies_in.all().first():
            peer_group.route_policy_in = peer_group.route_policies_in.all().first()
            peer_group.save()
        if peer_group.route_policies_out.all().first():
            peer_group.route_policy_out = peer_group.route_policies_out.all().first()
            peer_group.route_policy_out.save()

    for bgp_session in DeviceBGPSession.objects.all():
        if bgp_session.route_policies_in.all().first():
            bgp_session.route_policy_in = bgp_session.route_policies_in.all().first()
            bgp_session.save()

        if bgp_session.route_policies_out.all().first():
            bgp_session.route_policy_out = bgp_session.route_policies_out.all().first()
            bgp_session.save()

    for afisafi in AfiSafi.objects.all():
        if afisafi.route_policies_in.all().first():
            afisafi.route_policy_in = afisafi.route_policies_in.all().first()
            afisafi.save()
        if afisafi.route_policies_out.all().first():
            afisafi.route_policy_out = afisafi.route_policies_out.all().first()
            afisafi.save()


def save_route_pol_m2m(apps, schema):
    # This should do the reverse
    BGPPeerGroup = apps.get_model("netbox_cmdb", "BGPPeerGroup")
    DeviceBGPSession = apps.get_model("netbox_cmdb", "DeviceBGPSession")
    AfiSafi = apps.get_model("netbox_cmdb", "AfiSafi")

    for peer_group in BGPPeerGroup.objects.all():
        if peer_group.route_policy_in:
            peer_group.route_policies_in.add(peer_group.route_policy_in)

        if peer_group.route_policy_out:
            peer_group.route_policies_out.add(peer_group.route_policy_out)

    for bgp_session in DeviceBGPSession.objects.all():
        if bgp_session.route_policy_in:
            bgp_session.route_policies_in.add(bgp_session.route_policy_in)

        if bgp_session.route_policy_out:
            bgp_session.route_policies_out.add(bgp_session.route_policy_out)

    for afisafi in AfiSafi.objects.all():
        if afisafi.route_policy_in:
            afisafi.route_policies_in.add(afisafi.route_policy_in)

        if afisafi.route_policy_out:
            afisafi.route_policies_out.add(afisafi.route_policy_out)


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_cmdb", "0010_add_new_route_policy_field"),
    ]

    operations = [migrations.RunPython(save_route_pol_fk, save_route_pol_m2m)]
