# Generated by Django 4.0.7 on 2022-11-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0016_bgpsession_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgppeergroup',
            name='maximum_prefixes',
        ),
    ]
