# Generated by Django 4.0.7 on 2022-11-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0017_remove_bgppeergroup_maximum_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgppeergroup',
            name='remote_asn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)sremote_asn', to='netbox_cmdb.asn'),
        ),
    ]
