# Generated by Django 4.0.8 on 2022-12-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0020_alter_afisafi_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afisafi',
            name='device_bgp_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afi_safis', to='netbox_cmdb.devicebgpsession'),
        ),
    ]
