# Generated by Django 4.0.8 on 2023-01-11 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0023_alter_bgpglobal_ecmp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpglobal',
            name='ecmp_maximum_paths',
            field=models.PositiveIntegerField(default=32, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
