# Generated by Django 4.0.8 on 2023-03-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0060_alter_l2vpn_slug'),
        ('netbox_cmdb', '0025_alter_bgpcommunitylist_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicebgpsession',
            name='local_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_address', to='ipam.ipaddress'),
        ),
    ]
