# Generated by Django 4.0.8 on 2023-04-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0027_remove_bgpcommunitylistterm_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefixlistterm',
            name='decision',
        ),
    ]
