# Generated by Django 4.0.8 on 2023-08-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0030_alter_routepolicyterm_set_as_path_prepend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpsession',
            name='status',
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='state',
            field=models.CharField(default='staging', max_length=50),
        ),
        migrations.AddField(
            model_name='devicebgpsession',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
