# Generated by Django 4.0.8 on 2023-08-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0031_remove_bgpsession_status_bgpsession_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpsession',
            name='monitoring_state',
            field=models.CharField(default='disabled', max_length=50),
        ),
    ]
