# Generated by Django 4.0.8 on 2023-08-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0032_bgpsession_monitoring_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VRF',
        ),
    ]
