# Generated by Django 3.2.5 on 2021-08-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_cmdb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circuit",
            fields=[
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
