# Generated by Django 3.2.8 on 2021-11-04 16:22

from django.db import migrations, models
import django.db.models.deletion
import ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0133_port_colors'),
        ('netbox_cmdb', '0003_add_bgp_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGPCommunityList',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgpcommunitylistdevice', to='dcim.device')),
            ],
            options={
                'verbose_name_plural': 'BGP community lists',
                'unique_together': {('name', 'device')},
            },
        ),
        migrations.CreateModel(
            name='PrefixList',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefixlistdevice', to='dcim.device')),
            ],
            options={
                'unique_together': {('name', 'device')},
            },
        ),
        migrations.AlterModelOptions(
            name='routepolicy',
            options={'verbose_name_plural': 'Route Policies'},
        ),
        migrations.RemoveField(
            model_name='devicebgpsession',
            name='route_policy_in',
        ),
        migrations.RemoveField(
            model_name='devicebgpsession',
            name='route_policy_out',
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgppeergroupdevice', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='enforce_first_as',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='devicebgpsession',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devicebgpsession',
            name='enforce_first_as',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routepolicy',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routepolicydevice', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='routepolicy',
            name='device_bgp_session_in',
            field=models.ManyToManyField(blank=True, related_name='routepolicy_in', to='netbox_cmdb.DeviceBGPSession'),
        ),
        migrations.AddField(
            model_name='routepolicy',
            name='device_bgp_session_out',
            field=models.ManyToManyField(blank=True, related_name='routepolicy_out', to='netbox_cmdb.DeviceBGPSession'),
        ),
        migrations.AlterField(
            model_name='bgppeergroup',
            name='asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_cmdb.asn'),
        ),
        migrations.AlterField(
            model_name='bgppeergroup',
            name='maximum_prefixes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bgppeergroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='devicebgpsession',
            name='asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_cmdb.asn'),
        ),
        migrations.AlterField(
            model_name='devicebgpsession',
            name='maximum_prefixes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routepolicy',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='routepolicy',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='bgppeergroup',
            unique_together={('device', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='routepolicy',
            unique_together={('device', 'name')},
        ),
        migrations.RemoveField(
            model_name='bgppeergroup',
            name='route_policy_in',
        ),
        migrations.RemoveField(
            model_name='bgppeergroup',
            name='route_policy_out',
        ),
        migrations.CreateModel(
            name='RoutePolicyTerm',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('decision', models.CharField(default='permit', max_length=10)),
                ('from_bgp_community', models.CharField(blank=True, max_length=100)),
                ('from_source_protocol', models.CharField(blank=True, max_length=32)),
                ('from_route_type', models.CharField(blank=True, max_length=32)),
                ('from_local_pref', models.PositiveBigIntegerField(blank=True, null=True)),
                ('set_local_pref', models.PositiveBigIntegerField(blank=True, null=True)),
                ('set_community', models.CharField(blank=True, max_length=100)),
                ('set_origin', models.CharField(blank=True, max_length=32)),
                ('set_metric', models.PositiveBigIntegerField(blank=True, null=True)),
                ('set_large_community', models.CharField(blank=True, max_length=100)),
                ('set_as_path_prepend', models.CharField(blank=True, max_length=100)),
                ('set_next_hop', ipam.fields.IPAddressField(blank=True, null=True)),
                ('from_bgp_community_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_cmdb.bgpcommunitylist')),
                ('from_prefix_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_cmdb.prefixlist')),
                ('route_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_policy', to='netbox_cmdb.routepolicy')),
            ],
            options={
                'verbose_name_plural': 'Route Policy terms',
                'unique_together': {('route_policy', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='PrefixListTerm',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('decision', models.CharField(default='permit', max_length=32)),
                ('prefix', ipam.fields.IPNetworkField()),
                ('le', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prefix_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefix_list', to='netbox_cmdb.prefixlist')),
            ],
            options={
                'unique_together': {('prefix_list', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='BGPCommunityListTerm',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('decision', models.CharField(default='permit', max_length=32)),
                ('community', models.CharField(max_length=100)),
                ('bgp_community_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgp_community_list', to='netbox_cmdb.bgpcommunitylist')),
            ],
            options={
                'verbose_name_plural': 'BGP community list terms',
                'unique_together': {('bgp_community_list', 'sequence')},
            },
        ),
    ]
