# Generated by Django 3.2.8 on 2021-12-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_cmdb', '0008_prefixlist_ip_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routepolicy',
            name='device_bgp_session_in',
        ),
        migrations.RemoveField(
            model_name='routepolicy',
            name='device_bgp_session_out',
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='route_policies_in',
            field=models.ManyToManyField(blank=True, related_name='bgppeergroup_in', to='netbox_cmdb.RoutePolicy'),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='route_policies_out',
            field=models.ManyToManyField(blank=True, related_name='bgppeergroup_out', to='netbox_cmdb.RoutePolicy'),
        ),
        migrations.AddField(
            model_name='devicebgpsession',
            name='route_policies_in',
            field=models.ManyToManyField(blank=True, related_name='devicebgpsession_in', to='netbox_cmdb.RoutePolicy'),
        ),
        migrations.AddField(
            model_name='devicebgpsession',
            name='route_policies_out',
            field=models.ManyToManyField(blank=True, related_name='devicebgpsession_out', to='netbox_cmdb.RoutePolicy'),
        ),
        migrations.CreateModel(
            name='AfiSafi',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('afi_safi_name', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afisafi', to='contenttypes.contenttype')),
                ('route_policies_in', models.ManyToManyField(blank=True, related_name='afisafi_in', to='netbox_cmdb.RoutePolicy')),
                ('route_policies_out', models.ManyToManyField(blank=True, related_name='afisafi_out', to='netbox_cmdb.RoutePolicy')),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'afi_safi_name')},
            },
        ),
    ]
