# Generated by Django 3.2.11 on 2022-01-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0011_migrate_route_policies_to_route_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afisafi',
            name='route_policies_in',
        ),
        migrations.RemoveField(
            model_name='afisafi',
            name='route_policies_out',
        ),
        migrations.RemoveField(
            model_name='bgppeergroup',
            name='route_policies_in',
        ),
        migrations.RemoveField(
            model_name='bgppeergroup',
            name='route_policies_out',
        ),
        migrations.RemoveField(
            model_name='devicebgpsession',
            name='route_policies_in',
        ),
        migrations.RemoveField(
            model_name='devicebgpsession',
            name='route_policies_out',
        ),
    ]
