# Generated by Django 3.2.11 on 2022-02-28 13:20

from django.db import migrations
import netbox_cmdb.fields


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0012_remove_old_route_policies_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepolicyterm',
            name='set_next_hop',
            field=netbox_cmdb.fields.CustomIPAddressField(blank=True, null=True),
        ),
    ]
