# Generated by Django 4.0.5 on 2022-07-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0014_alter_afisafi_content_type_alter_afisafi_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicebgpsession',
            old_name='asn',
            new_name='local_asn',
        ),
        migrations.AlterField(
            model_name='devicebgpsession',
            name='local_asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)slocal_asn', to='netbox_cmdb.asn'),
        ),
        migrations.RenameField(
            model_name='bgppeergroup',
            old_name='asn',
            new_name='remote_asn',
        ),
        migrations.AlterField(
            model_name='bgppeergroup',
            name='remote_asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)sremote_asn', to='netbox_cmdb.asn'),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='local_asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)slocal_asn', to='netbox_cmdb.asn'),
        ),
    ]
