# Generated by Django 4.0.8 on 2022-12-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0161_cabling_cleanup'),
        ('netbox_cmdb', '0021_alter_afisafi_device_bgp_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGPGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('router_id', models.CharField(blank=True, default='', max_length=100)),
                ('ebgp_administrative_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('ibgp_administrative_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('graceful_restart', models.BooleanField()),
                ('graceful_restart_time', models.PositiveIntegerField(blank=True, null=True)),
                ('ecmp', models.BooleanField()),
                ('ecmp_maximum_paths', models.PositiveIntegerField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sdevice', to='dcim.device')),
                ('local_asn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)slocal_asn', to='netbox_cmdb.asn')),
            ],
            options={
                'verbose_name': 'BGP global configuration',
            },
        ),
    ]
