# Generated by Django 4.0.8 on 2023-01-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0022_bgpglobal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpglobal',
            name='ecmp',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bgpglobal',
            name='ecmp_maximum_paths',
            field=models.PositiveIntegerField(default=32),
        ),
    ]
