# Generated by Django 4.0.8 on 2023-02-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0161_cabling_cleanup'),
        ('netbox_cmdb', '0024_alter_bgpglobal_ecmp_maximum_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpcommunitylist',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sdevice', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='bgppeergroup',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sdevice', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='prefixlist',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sdevice', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='routepolicy',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sdevice', to='dcim.device'),
        ),
    ]
