# Generated by Django 4.0.8 on 2023-03-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0025_alter_bgpcommunitylist_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicebgpsession',
            name='send_community',
            field=models.CharField(default='BOTH', max_length=10),
        ),
    ]
