ARG python_ver=3.9
FROM python:${python_ver}

ARG netbox_ver=v3.3.10
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

RUN groupadd -g 1000 netbox && useradd -m -u 1000 -g netbox netbox
RUN mkdir -p /opt/netbox /source /sdist && chown netbox:netbox /opt/netbox /source /sdist
USER netbox

# -------------------------------------------------------------------------------------
# Install NetBox
# -------------------------------------------------------------------------------------
RUN git clone --single-branch --branch ${netbox_ver} https://github.com/netbox-community/netbox.git /opt/netbox/ && \
    cd /opt/netbox/ && \
    pip install -r /opt/netbox/requirements.txt

# Work around https://github.com/rq/django-rq/issues/421
RUN pip install django-rq==2.3.2

# -------------------------------------------------------------------------------------
# Build a tar.gz archive of Netbox Plugins
# -------------------------------------------------------------------------------------
WORKDIR /source
COPY --chown=netbox:netbox . /source

RUN ./develop/build-plugins.sh
